name: Publish Rust Builder Image

on:
  push:
    branches:
      - main
    paths:
      - docker/rust/**

jobs:
  publish:
    uses: ./.github/workflows/publish-images.yml
    with:
      image: fisirc/rust-builder
      labels: |
        maintainer=luedu1103
        org=fisirc
        template=rust
      dockerfile: docker/rust/Dockerfile
      context: docker/rust
